// Define permissions constants
// Format: resource_action
export const PERMISSIONS = {
  // Global
  ALL: 'all', // Super admin permission

  // Leads
  LEADS_READ: 'leads_read',
  LEADS_WRITE: 'leads_write',

  // Conversations (Chat/WhatsApp)
  CONVERSATIONS_READ: 'conversations_read',
  CONVERSATIONS_WRITE: 'conversations_write',

  // Students
  STUDENTS_READ: 'students_read',
  STUDENTS_WRITE: 'students_write',

  // Tickets/Support
  TICKETS_READ: 'tickets_read',
  TICKETS_WRITE: 'tickets_write',

  // Reports/Dashboard
  REPORTS_READ: 'reports_read',
} as const

// Role to Permissions Mapping
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  'admin': [PERMISSIONS.ALL],
  'org:admin': [PERMISSIONS.ALL],

  'sdr': [
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_WRITE,
  ],
  'org:sdr': [
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_WRITE,
  ],

  'cs': [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_WRITE,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_WRITE,
    PERMISSIONS.REPORTS_READ,
  ],
  'org:cs': [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_WRITE,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_WRITE,
    PERMISSIONS.REPORTS_READ,
  ],

  'support': [
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_WRITE,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_WRITE,
    PERMISSIONS.STUDENTS_READ,
  ],
  'org:support': [
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_WRITE,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_WRITE,
    PERMISSIONS.STUDENTS_READ,
  ],
}
